language: node_js
sudo: false
node_js:
  - "0.10"
  - 0.12
  - iojs
before_install:
  - npm install -g grunt-cli
notifications:
  email:
    recipients:
      - andris@kreata.ee
      - github+2015@josef-froehle.de
    on_success: change
    on_failure: change
